---
functional:
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика
  - сайт должен быть доступен на различных устройствах
  - адаптивная верстка магазина, чтобы он был удобным на мобильных устройствах
  - магазин - это SPA приложение, которое не перезагружает страницу
  - сайт должен иметь мобильную версию
  - пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - пользователь должен иметь возможность искать товары по ключевому слову или категории
  - на странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - на странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге
  - на странице корзины пользователь может оформить заказ с переходом на страницу оплаты
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
implicit:
  - в графе цена значение "до" должно быть больше чем "от". Значение "от" и "до" не могут быть отрицательным
  - кнопка "в наличии" не нужна, если товаров не в наличии отсутствуют
  - при выборе разных категорий не меняется список производителей или список производителей не соответстует выбранной категории
  - список производителей не реагирует на список диапозона цена, фильтр неинформативен
  - отсутствует постраничная навигация
  - список товаров не адаптивный при разрешении экрана full hd 
  - кнопка "добавить в корзину" не информативна 
  - нет возможности задать вопрос о доставке, способах оплаты, возврате товара 
