---
functional:
  - интерфейс магазина по продаже товаров с просмотром, фильтрацией товаров и добавлением их в корзину
  - адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - SPA приложение, которое не перезагружает страницу
  - пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - на странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. Корзина хранится в сессии браузера.
  - пользователь должен иметь возможность искать товары по ключевому слову или категории
  - пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
implicit:
  - в графе цена значение "до" должно быть больше чем "от". Значение "от" и "до" не могут быть отрицательным
  - требование 6
  - кнопка "в наличии" не нужна, если товаров не в наличии отсутствуют
  - при выборе разных категорий не меняется список производителей или список производителей не соответстует выбранной категории
  - список производителей не реагирует на список диапозона цена, фильтр неинформативен
  - отсутствует постраничная навигация
  
